def createDictionary():
        chapOneVocab = {"El/la abogado/a": "lawyer",
                        "El/la activista": "Activist",
                        "El ladron/la ladrona": "thief",
                        "El/la manifestante": "demonstrator",
                        "El/la politico/a": "Politician",
                        "El/la presidente/a": "president",
                        "El/la terrorista": "terrorist", "La Victima": "Victim",
                        "La amenaza": "Threat",
                        "El arma": "Weapon", "El escandalo": "scandal",
                        "La inseguridad": "insecurity", "El temor": "fear",
                        "El terrorismo": "terrorism", "La violencia": "Violence",
                        "Chantajear": "To blackmail", "Destrozar": "To destroy",
                        "Espiar": "To spy", "Huir": "To flee",
                        "Pelear": "To fight", "Secuestrar": "To kidnap",
                        "El abuso": "abuse", "La armada": "navy",
                        "La bandera": "flag", "La creencia": "belief",
                        "La crueldad": "cruelty", "La Democracia": "democracy",
                        "La Dictadura": "Dictatorship", "El ejercito": "army",
                        "El gobierno": "government",
                        "la guerra civil": "civil war",
                        "el partido politico": "political party",
                        "la paz": "peace", "el poder": "power",
                        "la politica": "politics",
                        "las relacione exteriories": "foreign relations",
                        "la victoria": "victory",
                        "dedicarse": "to devote oneself to",
                        "elegir": "to elect",
                        "ganar/perder las elecciones": "to win/lose elections",
                        "gobernar": "to govern", "influir": "to influence",
                        "votar": "to vote", "conservador": "conservative",
                        "liberal": "liberal", "pacifico": "peaceful",
                        "pacifista": "pacifist", "la injusticia": "injustice",
                        "la libertad": "freedom", "la lucha": "struggle",
                        "el tribunal": "court", "abusar": "to abuse",
                        "aprobar una ley": "to pass a law",
                        "convocar": "to summon", "defender": "to defend",
                        "derogar": "to abolish", "encarcelar": "to imprison",
                        "juzgar": "to judge", "analfabeto": "illiterate",
                        "desigual": "unequal", "injusto": "unfair",
                        "oprimido": "oppressed"}

        return chapOneVocab
