def createDictionary():
        chapFourVocab = {"la aficionada": "fan", "el alpinismo/andinismo":
                         "mountain climbing", "la atleta/deportista": "athlete",
                         "el boliche": "bowling", "la carrera": "race",
                         "el club deportivo": "sports club",
                         "los deportes extremos": "extreme sports",
                         "el equipo": "team",
                         "el esqui alpino": "downhill/cross country skiing",
                         "apostar": "to bet", "empatar": "to tie",
                         "ganar/perder un partido": "to win/lose a game",
                         "gritar": "to shout", "lastimar": "to injure",
                         "marcar(un gol)": "to score(a goal)",
                         "silbar": "to whistle", "vencer": "to defeat",
                         "el aguafiesta": "party pooper", "el anfitrion": "host",
                         "el billar": "billards", "el boleto": "ticket",
                         "las cartas": "(playing)cards", "la comedia": "comedy",
                         "el concierto": "concert",
                         "el conjunto/grupo musical": "musical group",
                         "los dardos": "darts", "el espectaculo": "spectator",
                         "la feria": "fair", "el juego de mesa": "board game",
                         "la loteria": "lottery", "la musica": "musician",
                         "la obra de teatro": "theater play",
                         "el ocio": "leisure",
                         "el parque de atracciones": "amusement park",
                         "los ratos libres": "free time",
                         "el recreo": "recreation",
                         "el teatro": "theater", "el videojuego": "video game",
                         "actuar": "to act", "aplaudir": "to applaud",
                         "brindar": "to toast", "celebrar": "to celebrate",
                         "charlar": "to chat", "coleccionar": "to collect",
                         "consequire(entradas)": "to get(tickets)",
                         "correr la voz": "to spread the word",
                         "divertirse": "to have a good time",
                         "entretenerse": "to amuse oneself",
                         "estrenar(una pelicula)": "to release (a movie)",
                         "festejar": "to celebrate",
                         "hacer cola": "to wait in line",
                         "poner un disco compacto": "to play a CD",
                         "reunirse": "to get together",
                         "salir (a comer/a tomar algo)":
                             "to go out (to eat/have a drink)",
                         "valer la pena": "to be worth it", "aburrido": "boring",
                         "agotado": "sold out", "animado": "lively",
                         "entretenido": "entertaining"}

        return chapFourVocab
