def createDictionary():
        chapThreeVocab = {"la arroba": "@ symbol", "el blog": "blog",
                          "el busacador": "search engine",
                          "la camara digital": "digital camera",
                          "el CD-ROM": "CD-ROM", "el ciberspacio": "cyber space",
                          "la computadora portatil": "laptop",
                          "la contrasena": "password",
                          "el corrector ortografico": "spell checker",
                          "la direccion electronica": "email address",
                          "el enlace": "link", "la herramienta": "Tool",
                          "la informatica": "computer science",
                          "el mensaje (de texto)": "text message",
                          "el nombre de usuario": "username",
                          "el programa de computacion": "software",
                          "la red": "the Web",
                          "el reproductor de MP3/DVD": "MP3/DVD Player",
                          "el telefono celular": "cell phone",
                          "adjuntar (un archivo)": "to attach (a file)",
                          "borrar": "to delete", "descargar":
                          "to download", "grabar (un CD)": "to burn (a CD)",
                          "guardar": "to save", "subir": "to upload",
                          "avanzado": "advanced", "en linea": "online",
                          "inalambrico": "wireless", "innovador": "innovative",
                          "revolucionario": 'revolutionary', 'el ADN': 'DNA',
                          'el avance': 'advance', 'la celula': 'cell',
                          "el desafio": "challenge",
                          "el descubrimiento": "discovery",
                          "el experimento": "experiment", "el gen": "gene",
                          "la genetica": "genetics", "el invento": "invention",
                          "la novedad": "new development", "la patente":
                              "patent", "la teoria": "theory",
                          "alcanzar": "to reach", "clonar": "to clone",
                          "comprobar": "to prove", "contribuir": "to contribute",
                          "crear": "to create", "curar": "to cure",
                          "fabricar": "to manufacture",
                          "inventar": "to invent", "bioquimico": "biochemical",
                          "especializado": "specialized",
                          "etico": "ethical", "el agujero negro": "black hole",
                          "el espacio": "space",
                          "la estrella fugaz": "shooting star",
                          "la galaxia": "galaxy", "la gravedad": "gravity",
                          "el planeta": "planet", "la supervivencia": "survival",
                          "el telescopio": "telescope",
                          "el transbordador espacial": "space shuttle",
                          "aterrizar": "to land", "explorar": "to explore",
                          "extraterrestre": "alien", "la astronauta":
                              "astronaut",  "la astronoma": "astronomer",
                          "el biologo": "biologist", "la cientifica":
                              "scientist", "el fisico": "physicist",
                          "la ingeniera": "engineer",
                          "el investigador": "researcher",
                          "el matematico": "mathematician",
                          "la bioquimica": "biochemist"}

        return chapThreeVocab
