def createDictionary():
        chapTwoVocab = {"el almacen": "department store", "el aumento de sueldo":
                        "pay raise", "la compania": "company", "el desempleo":
                        "unemployment", "la empressa": "company",
                        "el horario de trabajo": "work schedule",
                        "el impuesto": "tax", "el mercado": "market",
                        "el presupuesto": "budget", "el puesto": "position",
                        "la reunion": "meeting", "el sindicato": "labor union",
                        "el sueldo": "minimum wage", "acosar": "to harass",
                        "administrar": "to manage", "ascender": "to rise",
                        "contratar": "to hire", "despedir": "to fire",
                        "estar a la/en venta": "to be for sale",
                        "estar bajo presion": "to be under pressure",
                        "exigir": "to demand",
                        "ganarse la vida": "to earn a living",
                        "jubilarse": "to retire", "renunciar": "to quit",
                        "solicitar": "To apply for",
                        "tener conexiones": "to have connections",
                        "administrativo": "administrative",
                        "incapaz": "incapable", "desempleado": "unemployed",
                        "perezoso": "lazy", "trabajador": "hard-working",
                        "los ahorros": "savings", "la bancarrota": "bankruptcy",
                        "la bolsa de valores": "stock market",
                        "el cajero automatico": "ATM",
                        "la crisis economica": "economic crisis",
                        "la cuenta corriente": "checking account",
                        "la cuentat de ahorros": "savings account",
                        "la deuda": "debt", "la pobreza": "poverty",
                        "la riqueza": "wealth",
                        "la tarjeta de credito": "credit card",
                        "la tarjeta de debito": "debit card",
                        "ahorrar": "to save",
                        "aprovechar": "to take advantage of",
                        "cobrar": "to charge, to be paid",
                        "depositar": "to deposit", "gastar": "to spend",
                        "invertir": "to invest", "pedir": "to borrow",
                        "prestar": "to lend",
                        "a corto/largo plazo": "short/long term",
                        "agotado": "exhausted", "dispuesto": "ready",
                        "estresado": "stressed", "exitoso": "successful",
                        "financiero": "financial", "el asesor": "consultant",
                        "el contador": "accountant", "el dueno": "owner",
                        "el ejecutivo": "executiev", "el empleado": "employee",
                        "el gerente": "manager",
                        "el hombre de negocios": "businessman",
                        "el obrero": "blue collar worker", "el socio": "partner",
                        "el vendedor": "salesman"}

        return chapTwoVocab
